### ISSUE TITLE
自定义插件如何定义多个输出

### ISSUE THREAD

**Issue by fengguibinyn** [thfylsty/FastBEV#5]
在自定义插件中,forward函数如何定义多个输出

**Comment by thfylsty** [comment]
> 在自定义插件中,forward函数如何定义多个输出

output[0]
output[1]
output[2]即可将多个值赋给输出。在pytorch导出的时候，也需要return 多个输出。

**Comment by fengguibinyn** [comment]
c++那边理解,python那变,我写return多个 报错了
class ProjectPlugin(torch.autograd.Function):

    @staticmethod
    def symbolic(g, input):
        return g.op("Plugin::preject", input, name_s='Project2Dto3D', info_s='' )

    @staticmethod
    def forward(ctx, input ):

        # input: [bs*n_cams, h, w, c]
        # projection: [bs*n_cams, 3, 4]
        # output: [bev_h, bev_w, z, c']
        return torch.ones((1 ,64, 200, 200, 4)), torch.zeros((1 ,64, 200, 200, 4)), torch.ones((1 ,64, 200, 200, 4)), torch.ones((1 ,64, 200, 200, 4))
RuntimeError: symbolic for ProjectPlugin produced an incorrect number of outputs (expected 4, but got 1)

**Comment by thfylsty** [comment]
def symbolic(g, input, projection):
        return g.op("Plugin", input, projection, name_s='Project2Dto3D', info_s='',outputs=2)

**Comment by fengguibinyn** [comment]
t
